### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by monteksingh** [ibm-cloud-security/acme-account-creation-tool#19]
I am using ubuntu machine with Intel processor

When I run 

 sudo ./acme-account-creation-tool-linux-amd64 -e email_ID -o my-letsencrypt -d letsencrypt-prod -k pkcs8.key

I get 
sudo: ./acme-account-creation-tool-linux-amd64: command not found

**Comment by voguy** [comment]
There is no issue from my side. Are you in the folder where is located the binary ? If not, ensure to use the correct path in your command.

**Comment by IdanAdar** [comment]
This issue was previously resolved 1x1.
